#!/usr/bin/env bash
# GTK 3, GTK 4 and libadwaita applications.
#
# A GTK app resolves colors from two places: the gsettings interface keys, and
# the @define-color palette in gtk.css. Setting both means an app that honours
# only one of them still lands on-theme, which is the common case -- libadwaita
# apps read gsettings for their chrome and gtk.css for custom CSS.
#
# Nothing here duplicates what Omarchy already does. omarchy-theme-set-gnome
# sets color-scheme and the GTK *theme name*; the existing app-theme hook owns
# the cursor and icon themes. This handler adds only what neither can: a real
# accent color, and a surface/selection palette for apps that read gtk.css.
#
# One block, one definition per property. An earlier draft wrote a second
# wallpaper-tinted block that re-declared the selection colors, which meant the
# theme's values were silently overridden by cascade order rather than by
# intent. The wallpaper palette is now folded into the single block at generation
# time, so what a property resolves to is decided in one place.

# Write a gsettings key only when it differs.
#
# The comparison is not only an optimisation. gsettings set is a dconf write that
# invalidates caches in every running GTK app, so rewriting an unchanged key
# makes every open app re-read its settings for no reason. During a theme change,
# which fires a dozen hooks in parallel, that is the difference between a switch
# that lands quietly and one that makes every window flicker.
set_gsetting_if_changed() {
  local schema="$1" key="$2" value="$3" current

  gsettings writable "$schema" "$key" >/dev/null 2>&1 || return 0

  current=$(gsettings get "$schema" "$key" 2>/dev/null) || return 0

  # gsettings get prints the value with its GVariant type: a string comes back
  # single-quoted, an enum comes back bare. Accept either form so the comparison
  # does not report a false change and rewrite on every run.
  [[ $current == "'$value'" || $current == "$value" ]] && return 0

  gsettings set "$schema" "$key" "$value" 2>/dev/null
}

# Emit the gtk.css block on stdout.
#
# Takes no arguments and reads the palette from the environment, so the theme
# pass and the wallpaper pass generate identical structure and cannot drift.
#
# One accent, resolved once. ACCENT_UNIFIED is the theme's accent after being
# reconciled with the wallpaper, so the selection color here is the same family
# as the bar's and the terminals' -- the earlier draft took the wallpaper's
# primary directly and put a beige highlight under a blue desktop.
gtk_css_body() {
  local accent=$ACCENT_UNIFIED
  local selection_fg border border_dim source_desc

  # Borders and the unfocused variant can carry a little more of the wallpaper
  # than the accent can, because a border is decoration rather than an identity:
  # a wallpaper-derived border that disagrees with the theme reads as depth, not
  # as a second palette. Still gated on the wallpaper actually existing.
  border=$LIGHTER_BACKGROUND
  border_dim=$DARK_BACKGROUND
  source_desc="theme ${AUTOSYNC_THEME_NAME:-unknown}"

  if [[ $WALL_SOURCE == better-bar ]]; then
    border=$(mix_hex "$LIGHTER_BACKGROUND" "$WALL_OUTLINE" 35%) || border=$LIGHTER_BACKGROUND
    border_dim=$(mix_hex "$DARK_BACKGROUND" "$WALL_SURFACE_HIGH" 35%) || border_dim=$DARK_BACKGROUND
    source_desc="$source_desc + wallpaper ${AUTOSYNC_BACKPAPER_NAME:-palette}"
  fi

  # Measured against the accent that is actually being written, not against the
  # theme's selection: the wallpaper moves the accent, and carrying the theme's
  # on-selection text over would put it on a color it was never checked against.
  selection_fg=$(best_contrast_on "$accent" "$FOREGROUND" '#000000' '#ffffff')

  cat <<CSS
/*
 * GTK palette from the active Omarchy theme: ${AUTOSYNC_THEME_NAME:-theme} ($MODE).
 * Sources: $source_desc.
 * Generated by omarchy-auto-sync. Edits inside the markers are overwritten;
 * anything outside them is yours and is left alone.
 */

@define-color theme_fg_color            $FOREGROUND;
@define-color theme_bg_color            $BACKGROUND;
@define-color theme_base_color          $BACKGROUND;
@define-color theme_text_color          $FOREGROUND;
@define-color theme_selected_bg_color   $accent;
@define-color theme_selected_fg_color   $selection_fg;
@define-color insensitive_fg_color      $MUTED;
@define-color insensitive_base_color    $DARK_BACKGROUND;
@define-color theme_unfocused_fg_color  $MUTED;
@define-color theme_unfocused_bg_color  $BACKGROUND;
@define-color borders                   $border;
@define-color unfocused_borders         $border_dim;
@define-color warning_color             $YELLOW;
@define-color error_color               $RED;
@define-color success_color             $GREEN;
@define-color window_bg_color           $BACKGROUND;
@define-color window_fg_color           $FOREGROUND;
@define-color view_bg_color             $BACKGROUND;
@define-color view_fg_color             $FOREGROUND;
@define-color text_color                $FOREGROUND;
@define-color selected_bg_color         $accent;
@define-color selected_fg_color         $selection_fg;
CSS
}

# Write the block into every gtk.css the user already has a directory for.
#
# Both GTK generations, newest first. The version directory is only written when
# it already exists: creating ~/.config/gtk-4.0 is not what makes an app dark,
# and creating config directories for toolkits the user does not have installed
# is litter.
apply_gtk_css() {
  local version dir target wrote=false

  for version in 4.0 3.0; do
    dir="$HOME/.config/gtk-$version"
    [[ -d $dir ]] || continue
    target="$dir/gtk.css"

    gtk_css_body | write_marked_block "$target" "gtk-$version" || return 1
    $AUTOSYNC_WROTE && wrote=true
  done

  $wrote && notify "Theme synced to GTK" \
    "Running GTK apps keep their old colors until they are restarted."
  return 0
}

apply_gtk() {
  command -v gsettings >/dev/null 2>&1 || {
    log "gsettings not available; skipping GTK settings"
    return 0
  }

  # prefer-dark / prefer-light are the only values GNOME accepts, and this is
  # what makes libadwaita draw a dark UI. Derived from the theme's mode rather
  # than passed through, because a theme with no mode key still classifies via
  # omarchy-theme-color's background-luminance fallback.
  set_gsetting_if_changed org.gnome.desktop.interface color-scheme \
    "$([[ $MODE == light ]] && printf 'prefer-light' || printf 'prefer-dark')"

  # GTK will not draw an arbitrary accent: org.gnome.desktop.interface
  # accent-color is an enum, and a value outside the enum is rejected outright.
  # gnome_accent_name maps the theme's exact accent onto the nearest one, which
  # is as close as a non-adwaita-gtk theme can get to its own accent while still
  # coloring every button and selection.
  set_gsetting_if_changed org.gnome.desktop.interface accent-color \
    "$(gnome_accent_name "$ACCENT_UNIFIED")"

  # cursor-theme, icon-theme and gtk-theme are deliberately absent. The
  # app-theme hook and omarchy-theme-set-gnome own those, and two writers on one
  # key means whichever hook runs last silently wins.
  return 0
}

# Wallpaper-only half.
#
# Separate from apply_gtk because a wallpaper change should not also restamp the
# gsettings half: those keys describe the theme, and rewriting them on every
# wallpaper change would invalidate dconf caches across the desktop for a
# palette that did not move. The CSS half is rewritten because its accent did.
apply_gtk_css_wallpaper() {
  [[ $WALL_SOURCE == better-bar ]] || {
    log "no wallpaper palette available; GTK css unchanged"
    return 0
  }
  apply_gtk_css
}
