#!/usr/bin/env bash
# Qt 5 and Qt 6 applications.
#
# Qt has no equivalent of gtk.css, and on Arch that leaves Kvantum as the usual
# answer -- which means installing a theme engine and a theme before a single
# dialog is recolored. This handler uses the qt5ct/qt6ct color scheme instead:
# it is a plain INI that the platform-theme plugin already reads, needs no engine,
# and covers the palette every stock Qt dialog uses.
#
# Qt apps only follow it when the platform theme plugin is active, which is what
# QT_QPA_PLATFORMTHEME selects. Writing the scheme without that is the most common
# way this appears not to work, so the plugin is also registered through
# ~/.config/environment.d/ -- the mechanism systemd-imported environments honor,
# and which a new session picks up without touching a shell rc file.
#
# Nothing is written unless qt5ct or qt6ct is actually installed. Creating
# ~/.config/qt6ct on a machine with no Qt tooling installed is litter, and the
# package-delta check re-runs this handler once a Qt toolchain appears.

qt_configured() {
  command -v qt5ct >/dev/null 2>&1 || command -v qt6ct >/dev/null 2>&1
}

# Qt color roles, mapped from the theme's semantic names.
#
# Qt's role names are its own, and they do not line up one-to-one with the theme's
# palette: ToolTipBase and AlternateBase and Mid are roles a theme does not name at
# all. Each is derived from the closest thing the theme does have, so the whole set
# comes from one source rather than from a hand-picked list of hex values that
# would drift from colors.toml.
qt_palette() {
  local surface=$LIGHTER_BACKGROUND
  local sunken=$DARK_BACKGROUND
  local accent=$ACCENT_UNIFIED
  local accent_text
  accent_text=$(best_contrast_on "$accent" "$FOREGROUND" '#000000' '#ffffff')

  cat <<INI
; Generated by omarchy-auto-sync. Edits are overwritten on the next theme change.
; Qt color scheme from the active Omarchy theme: ${AUTOSYNC_THEME_NAME:-theme} ($MODE).

[General]
Description=Omarchy ${AUTOSYNC_THEME_NAME:-theme}
Opacity=100
Override=false

[Background]
Normal=$BACKGROUND

[Colors]
Window=$surface
WindowText=$FOREGROUND
Base=$BACKGROUND
AlternateBase=$sunken
ToolTipBase=$sunken
ToolTipText=$FOREGROUND
Text=$FOREGROUND
Button=$surface
ButtonText=$FOREGROUND
BrightText=$([[ $MODE == light ]] && printf '#d20f39' || printf '#ea76cb')
Light=$(mix_hex "$surface" '#ffffff' 25%)
Midlight=$surface
Mid=$(mix_hex "$surface" '#000000' 25%)
Dark=$(mix_hex "$surface" '#000000' 45%)
Shadow=$DARKER_BACKGROUND
Link=$BLUE
LinkVisited=$MAGENTA
PlaceholderText=$MUTED
Accent=$accent
AccentText=$accent_text
Disabled=$MUTED
DisabledText=$(mix_hex "$MUTED" "$BACKGROUND" 50%)
INI
}

apply_qt() {
  [[ $AUTOSYNC_QT == true ]] || return 0

  if ! qt_configured && [[ ! -d $HOME/.config/qt5ct && ! -d $HOME/.config/qt6ct ]]; then
    log "no qt5ct/qt6ct installed; skipping Qt (it will be themed once one appears)"
    return 0
  fi

  local version wrote=false
  for version in 5 6; do
    local dir="$HOME/.config/qt${version}ct"
    # A config directory that already exists means the tool is configured. One
    # that does not is only created when the matching binary is installed, so an
    # unused directory never appears on a Qt-less machine.
    if [[ ! -d $dir ]] && ! command -v "qt${version}ct" >/dev/null 2>&1; then
      continue
    fi

    mkdir -p "$dir/colors" || continue

    qt_palette | write_if_changed "$dir/colors/Omarchy.conf" || continue
    $AUTOSYNC_WROTE && wrote=true

    # Point the tool at the scheme. Edited through qtct's own file rather than
    # its GUI: a rewritten [General] section with only this key is what qtct
    # expects, and hand-editing avoids a round trip through a settings dialog on
    # every theme change.
    write_if_changed "$dir/qt${version}ct.conf" <<CONF || continue
[General]
Color=Omarchy
CONF
    $AUTOSYNC_WROTE && wrote=true
  done

  # Register the platform theme plugin so the scheme above is honored. Written
  # only when absent, and as a whole file, because this one is ours.
  if [[ ! -f $HOME/.config/environment.d/90-omarchy-auto-sync.conf ]]; then
    write_if_changed "$HOME/.config/environment.d/90-omarchy-auto-sync.conf" <<'CONF' || true
# Managed by omarchy-auto-sync. Makes Qt applications read the qt5ct/qt6ct
# color scheme, which is how they get themed alongside the GTK apps.
QT_QPA_PLATFORMTHEME=qt5ct;qt6ct
CONF
  fi

  $wrote && log "Qt scheme written for qt5ct/qt6ct"
  return 0
}
