#!/usr/bin/env bash
# Omarchy shell plugins -- the QML widgets in the bar, panels, and overlays.
#
# Shell plugins are not ordinary applications and need almost nothing here. The
# shell loads colors.toml and shell.toml through its Color singleton, and every
# plugin that reads Color.* or Style.* follows a theme change with no help. That
# is the design, and it is why there is no generated config to write for them.
#
# What this handler does instead is answer the question the Color singleton
# cannot: which installed plugins will NOT follow the theme, and are there any
# new ones. A plugin that hardcodes a hex color instead of reading Color.accent
# keeps that color through every theme change, and it is invisible until you
# change the theme and notice one widget did not move.
#
# Both the stock plugins and the user's own are scanned, on every run. That is
# what covers plugins installed later: there is no registry to miss, because the
# filesystem is the registry. A plugin arriving from a dotfile sync into another
# user's machine is just a directory that appears, and the next theme change or
# update picks it up.
#
# Nothing here rewrites a plugin's source. Editing a plugin's QML to recolor it
# would be silently undone by `omarchy plugin clone` or a plugin update, and
# would break on the next release that renames a property. Reporting is the only
# thing that stays correct over time.

# Directories that hold installed shell plugins.
plugin_dirs() {
  printf '%s\n' \
    "$HOME/.config/omarchy/plugins" \
    "/usr/share/omarchy/shell/plugins"
}

# Count hardcoded hex colors in a plugin's QML.
#
# Only literal "#rrggbb" or "#rgb" in a property assignment or a color function
# counts. Hex inside a comment or a string is not a color and is skipped, and
# Alpha.qml-style 0xAARRGGBB integers are not matched because they are usually
# animation curves and version stamps rather than palette entries.
#
# The grep is limited to .qml and .js files: a plugin's own data files are more
# likely to carry an icon or a checksum than a color.
count_hardcoded_colors() {
  local plugin_dir="$1"
  local files

  # grep exits 1 when it matches nothing, which is the common case for a
  # well-behaved plugin. That is a count of zero, not a reason to return nothing:
  # an empty value would land in the report's table as a blank cell.
  files=$(grep -rlE '"#[0-9A-Fa-f]{6}"|:\s*#[0-9A-Fa-f]{3,6}\b|#[0-9A-Fa-f]{6}\b' \
    --include='*.qml' --include='*.js' "$plugin_dir" 2>/dev/null) || files=""

  [[ -n $files ]] || {
    printf '0'
    return 0
  }

  # shellcheck disable=SC2086
  grep -ohE '"#[0-9A-Fa-f]{6}"|#[0-9A-Fa-f]{6}\b' $files 2>/dev/null | sort -u | wc -l
}

# Does this plugin read the shell's theme singletons?
#
# A plugin that imports Color or Style is theme-aware even if it also carries a
# fallback literal, which is normal defensive QML. The distinction matters: a
# plugin with hardcoded colors AND no Color import is the one that will visibly
# fail to follow the theme, and a plugin with both is fine.
plugin_reads_theme() {
  local plugin_dir="$1" files

  files=$(grep -rlE 'Color\.[a-zA-Z]|Style\.[a-zA-Z]' \
    --include='*.qml' --include='*.js' "$plugin_dir" 2>/dev/null) || return 1

  [[ -n $files ]]
}

apply_shell_plugins() {
  local report_dir="$AUTOSYNC_STATE_DIR/auto-sync"
  local report="$report_dir/shell-plugins.md"

  mkdir -p "$report_dir" || {
    log "cannot create $report_dir"
    return 0
  }

  local dir manifest id name kind hardcoded theme_aware state
  local -a offenders=()
  local total=0 theme_aware_count=0

  # The report is regenerated from scratch each run so a plugin that has since
  # been fixed or removed disappears from it. Anything else turns the report into
  # a list of things that were once true.
  {
    printf '# Omarchy shell plugins\n\n'
    printf 'Generated by better-theme-sync. Not edited by hand.\n\n'
    printf 'Most shell plugins follow the active theme automatically: the shell reads\n'
    printf '`colors.toml` and `shell.toml` through its `Color` singleton, so a plugin\n'
    printf 'that uses `Color.*` or `Style.*` needs no configuration and is listed below\n'
    printf 'as theme-aware. A plugin that hardcodes hex colors and never reads those\n'
    printf 'singletons keeps its own colors through every theme change.\n\n'
    printf 'Theme: %s (%s)\n\n' "${AUTOSYNC_THEME_NAME:-unknown}" "$MODE"
    printf '| Plugin | Source | Hardcoded colors | Follows theme |\n'
    printf '| --- | --- | --- | --- |\n'
  } >"$report_dir/.shell-plugins.tmp"

  while IFS= read -r dir; do
    [[ -d $dir ]] || continue

    local plugin
    for plugin in "$dir"/*/; do
      [[ -d $plugin ]] || continue
      # A plugin is a directory with a manifest; anything else in these trees is
      # an asset directory or a leftover.
      [[ -f $plugin/manifest.json ]] || continue

      id=$(basename "$plugin")
      manifest=$(<"$plugin/manifest.json")

      # The manifest's own id is authoritative; the directory name is only a
      # fallback for a manifest that omits it.
      name=$(jq -r '.name // empty' <<<"$manifest" 2>/dev/null)
      [[ -n $name ]] || name=$id
      kind=$(jq -r '(.kinds // []) | join(", ")' <<<"$manifest" 2>/dev/null)
      [[ -n $kind && $kind != null ]] || kind="unknown"

      if [[ $dir == "$HOME/.config/omarchy/plugins" ]]; then
        state="user"
      else
        state="stock"
      fi

      hardcoded=$(count_hardcoded_colors "$plugin")
      if plugin_reads_theme "$plugin"; then
        theme_aware="yes"
        ((theme_aware_count++))
      else
        theme_aware="NO"
      fi

      ((total++))
      printf '| %s | %s (%s) | %s | %s |\n' "$name" "$id" "$state" "$hardcoded" "$theme_aware" \
        >>"$report_dir/.shell-plugins.tmp"

      # Only a plugin that both hardcodes colors and ignores the singletons is a
      # real finding. One or the other alone is fine.
      if [[ $theme_aware == NO && $hardcoded -gt 0 ]]; then
        offenders+=("$name")
      fi
    done
  done < <(plugin_dirs)

  {
    printf '\n%d plugin(s) scanned, %d theme-aware.\n' "$total" "$theme_aware_count"
    if ((${#offenders[@]} > 0)); then
      printf '\n## Will not follow the theme\n\n'
      printf 'These hardcode colors and never read Color/Style, so they keep their own\n'
      printf 'palette when the theme changes. To make one follow the theme, replace its\n'
      printf 'literal hex colors with the matching `Color.*` or `Style.*` property.\n\n'
      local offender
      for offender in "${offenders[@]}"; do
        printf -- '- %s\n' "$offender"
      done
    else
      printf '\nEvery scanned plugin reads the shell theme singletons.\n'
    fi
  } >>"$report_dir/.shell-plugins.tmp"

  write_if_changed "$report" <"$report_dir/.shell-plugins.tmp" || return 1
  rm -f "$report_dir/.shell-plugins.tmp"

  log "$total shell plugin(s) scanned, $theme_aware_count theme-aware"

  # Notify only when the offending set changes. A notification on every theme
  # switch would be noise, since the finding does not change between switches --
  # but a newly installed plugin that will not follow the theme is exactly the
  # moment the user wants to hear about it.
  local offenders_key="$report_dir/offenders"
  local current_key="${offenders[*]:-none}"

  if [[ -f $offenders_key ]] && [[ $(<"$offenders_key") == "$current_key" ]]; then
    return 0
  fi

  printf '%s\n' "$current_key" | write_if_changed "$offenders_key"

  if ((${#offenders[@]} > 0)); then
    notify "Shell plugin theme audit" \
      "${#offenders[@]} plugin(s) hardcode colors and will not follow the theme. Details: $report"
  else
    log "no shell plugin is locked out of the theme"
  fi
  return 0
}
